-- ----------------------------
-- Records of wilayahs
-- ----------------------------
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1007, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Surodinawan', 0, '35.76.01', '35.76.01.1007');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1001, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Kranggan', 0, '35.76.03', '35.76.03.1001');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1002, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Miji', 0, '35.76.03', '35.76.03.1002');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1006, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Prajurit Kulon', 0, '35.76.01', '35.76.01.1006');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1008, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Blooto', 0, '35.76.01', '35.76.01.1008');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1003, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Mentikan', 0, '35.76.01', '35.76.01.1003');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1004, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Kauman', 0, '35.76.01', '35.76.01.1004');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 1, 1005, 'Jawa Timur', 'Kota Mojokerto', 'Prajurit Kulon', 'Pulorejo', 0, '35.76.01', '35.76.01.1005');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1003, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Meri', 0, '35.76.03', '35.76.03.1003');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1001, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Gunung Gedangan', 0, '35.76.02', '35.76.02.1001');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1009, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Kedundung', 0, '35.76.02', '35.76.02.1009');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1008, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Balongsari', 0, '35.76.02', '35.76.02.1008');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1004, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Jagalan', 0, '35.76.03', '35.76.03.1004');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1005, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Sentanan', 0, '35.76.03', '35.76.03.1005');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 3, 1006, 'Jawa Timur', 'Kota Mojokerto', 'Kranggan', 'Purwotengah', 0, '35.76.03', '35.76.03.1006');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1004, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Gedongan', 0, '35.76.02', '35.76.02.1004');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1003, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Magersari', 0, '35.76.02', '35.76.02.1003');
INSERT INTO `wilayahs` ( kode_provinsi, kode_kota, kode_kecamatan, kode_kelurahan, nama_provinsi, nama_kota, nama_kecamatan, nama_kelurahan, is_deleted, kode_full_kec, kode_full_kel ) VALUES ( 35, 76, 2, 1010, 'Jawa Timur', 'Kota Mojokerto', 'Magersari', 'Wates', 0, '35.76.02', '35.76.02.1010');
